[package]
name = "nft_daemon"
version = "0.1.0"
edition = "2021"
authors = ["mfljefferson@example.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nft_shared = {path = "../nft_shared"}
